import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PageUserContextProvider } from "@/context/PageUserContext";
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from "@/components/ui/tooltip";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-background text-foreground">
                <main className="min-h-screen flex flex-col items-center">
                    <TooltipProvider delayDuration={250}>
                        {/* <PageUserContextProvider> */}
                        {children}
                        {/* </PageUserContextProvider> */}
                    </TooltipProvider>
                </main>
                <Toaster />
            </body>
        </html>
    );
}
