import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PageUserContextProvider } from "@/context/PageUserContext";
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from "@/components/ui/tooltip";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/custom/theme-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-background text-foreground">
                <main className="min-h-screen flex flex-col items-center">
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <TooltipProvider delayDuration={250}>
                            {children}
                        </TooltipProvider>
                    </ThemeProvider>
                </main>
                <Toaster />
            </body>
        </html>
    );
}
